import type { Iuser } from '@/app/interface/usersdata/Iusers';

export const userData: Iuser[] = [
  {
    id: 1,
    avatar: 'https://i.pravatar.cc/150?img=1',
    name: 'Sonair',
    mobile: '227-677-5702',
    country: 'Kokologo',
    mobileVerified: true,
    emailVerified: true,
    coins: 37,
    adsCount: 73,
  },
  {
    id: 2,
    avatar: 'https://i.pravatar.cc/150?img=2',
    name: 'Latlux',
    mobile: '372-617-9186',
    country: 'Wengang',
    mobileVerified: false,
    emailVerified: true,
    coins: 12,
    adsCount: 50,
  },
  {
    id: 3,
    avatar: 'https://i.pravatar.cc/150?img=3',
    name: 'Holdlamis',
    mobile: '484-260-0646',
    country: 'Rancaseneng',
    mobileVerified: true,
    emailVerified: true,
    coins: 86,
    adsCount: 17,
  },
  {
    id: 4,
    avatar: 'https://i.pravatar.cc/150?img=4',
    name: 'Zathin',
    mobile: '835-890-7148',
    country: 'Bosilovo',
    mobileVerified: true,
    emailVerified: false,
    coins: 8,
    adsCount: 97,
  },
  {
    id: 5,
    avatar: 'https://i.pravatar.cc/150?img=5',
    name: 'Namfix',
    mobile: '275-495-0379',
    country: 'Himanka',
    mobileVerified: false,
    emailVerified: true,
    coins: 81,
    adsCount: 69,
  },
  {
    id: 6,
    avatar: 'https://i.pravatar.cc/150?img=6',
    name: 'Opela',
    mobile: '735-794-7885',
    country: 'Sim',
    mobileVerified: false,
    emailVerified: false,
    coins: 30,
    adsCount: 31,
  },
  {
    id: 7,
    avatar: 'https://i.pravatar.cc/150?img=7',
    name: 'Transcof',
    mobile: '193-970-8892',
    country: 'Světlá nad Sázavou',
    mobileVerified: true,
    emailVerified: false,
    coins: 26,
    adsCount: 26,
  },
  {
    id: 8,
    avatar: 'https://i.pravatar.cc/150?img=8',
    name: 'Rank',
    mobile: '737-358-6401',
    country: 'Gibato',
    mobileVerified: true,
    emailVerified: true,
    coins: 95,
    adsCount: 14,
  },
  {
    id: 9,
    avatar: 'https://i.pravatar.cc/150?img=9',
    name: 'Rank',
    mobile: '112-249-7294',
    country: 'Stare Miasto',
    mobileVerified: true,
    emailVerified: true,
    coins: 62,
    adsCount: 62,
  },
  {
    id: 10,
    avatar: 'https://i.pravatar.cc/150?img=10',
    name: 'Asoka',
    mobile: '110-240-9333',
    country: 'Karangwaru',
    mobileVerified: true,
    emailVerified: true,
    coins: 86,
    adsCount: 62,
  },
  {
    id: 11,
    avatar: 'https://i.pravatar.cc/150?img=11',
    name: 'Overhold',
    mobile: '664-182-7757',
    country: '‘Abbāsābād',
    mobileVerified: true,
    emailVerified: true,
    coins: 44,
    adsCount: 38,
  },
  {
    id: 12,
    avatar: 'https://i.pravatar.cc/150?img=12',
    name: 'Sub-Ex',
    mobile: '795-404-4925',
    country: 'Río Grande',
    mobileVerified: true,
    emailVerified: true,
    coins: 45,
    adsCount: 60,
  },
  {
    id: 13,
    avatar: 'https://i.pravatar.cc/150?img=13',
    name: 'Tin',
    mobile: '132-727-9192',
    country: 'Senanga',
    mobileVerified: false,
    emailVerified: true,
    coins: 62,
    adsCount: 2,
  },
  {
    id: 14,
    avatar: 'https://i.pravatar.cc/150?img=14',
    name: 'Quo Lux',
    mobile: '337-227-0347',
    country: 'Bagombong',
    mobileVerified: false,
    emailVerified: true,
    coins: 94,
    adsCount: 37,
  },
  {
    id: 15,
    avatar: 'https://i.pravatar.cc/150?img=15',
    name: 'Asoka',
    mobile: '713-944-4634',
    country: 'Tlogowungu',
    mobileVerified: false,
    emailVerified: false,
    coins: 19,
    adsCount: 61,
  },
  {
    id: 16,
    avatar: 'https://i.pravatar.cc/150?img=16',
    name: 'Kanlam',
    mobile: '487-881-2880',
    country: 'Hässleholm',
    mobileVerified: true,
    emailVerified: false,
    coins: 58,
    adsCount: 8,
  },
  {
    id: 17,
    avatar: 'https://i.pravatar.cc/150?img=17',
    name: 'Zaam-Dox',
    mobile: '897-556-4293',
    country: 'Ketawang',
    mobileVerified: true,
    emailVerified: true,
    coins: 46,
    adsCount: 18,
  },
  {
    id: 18,
    avatar: 'https://i.pravatar.cc/150?img=18',
    name: 'Biodex',
    mobile: '954-425-5372',
    country: 'Monteros',
    mobileVerified: false,
    emailVerified: true,
    coins: 100,
    adsCount: 39,
  },
  {
    id: 19,
    avatar: 'https://i.pravatar.cc/150?img=19',
    name: 'Fintone',
    mobile: '664-694-5869',
    country: 'Heba',
    mobileVerified: true,
    emailVerified: true,
    coins: 72,
    adsCount: 19,
  },
  {
    id: 20,
    avatar: 'https://i.pravatar.cc/150?img=20',
    name: 'Bitwolf',
    mobile: '536-224-3684',
    country: 'Maxu',
    mobileVerified: false,
    emailVerified: false,
    coins: 9,
    adsCount: 7,
  },
];
